node01:
    image: cassandra:3.5
    ports:
        - "7000:7000"
        - "7001:7001"
        - "9042:9042"
        - "9160:9160"
        - "7199:7199"
    volumes:
        - ./data:/var/lib/cassandra
   
node02:
    image: cassandra:3.5
    ports:
        - "17000:7000"
        - "17001:7001"
        - "19042:9042"
        - "19160:9160"
        - "17199:7199"
    environment:
        - CASSANDRA_SEEDS=node01
    links:
     - node01:node01

node03:
    image: cassandra:3.5
    ports:
        - "27000:7000"
        - "27001:7001"
        - "29042:9042"
        - "29160:9160"
        - "27199:7199"
    environment:
        - CASSANDRA_SEEDS=node01
    links:
        - node01:node01
